"$schema" = 'https://starship.rs/config-schema.json'

# push-night color shema
# #f72585
# #7209b7
# #3a0ca3
# #4361ee
# #4cc9f0
# #57cc99
#
# old palette 
# #9A348E
# #DA627D
# #FCA17D
# #86BBD8
# #06969A
# #33658A
#
format = """
[](#f72585)\
$os\
$username\
[](fg:#f72585 bg:#7209b7 )\
$directory\
[](fg:#7209b7 bg:#3a0ca3)\
$git_branch\
$git_status\
[](fg:#3a0ca3 bg:#4361ee)\
$nodejs\
[](fg:#4361ee bg:#4361ee)\
$dotfiles\
[](fg:#4361ee bg:#4cc9f0)\
$docker_context\
[](fg:#4cc9f0 bg:#57cc99)\
$time\
[ ](fg:#57cc99)\
$character\
"""
#scan_ignore_paths = ["/mnt/smb"]
# Disable the blank line at the start of the prompt
#add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#f72585"
disabled = false # Disabled by default

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:black bg:#f72585"
style_root = "bg:red"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#7209b7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

 [git_branch]
 symbol = ""
 style = "bg:#3a0ca3"
 format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#3a0ca3"
format = '[$all_status$ahead_behind ]($style)'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"dotfiles" = " "
".config" = "󰨾 "

[docker_context]
symbol = " "
style = "bg:#4cc9f0"
format = '[ $symbol $context ]($style)'
detect_folders = [ "docker", "~/docker/", "pihole", "/home/push/docker/pihole" ]
only_with_files = false

[nodejs]
symbol = ""
style = "bg:#4361ee"

format = '[ $symbol ($version) ]($style)'
[character]
success_symbol = "[λ](bold #57cc99)"
error_symbol = "[λ](bold #f72585)"
# success_symbol = "[λ](bold green)"
# error_symbol = "[λ](bold red)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:black bg:#57cc99"
format = '[ $time ]($style)'
#format = '[ λ$time ]($style)'
#format = '[ ♥ $time ]($style)'
