-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AOC 24G2W1G3- SXINCHA005940",
  mode = "1920x1080@60.00",
  position = "4012x82",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AOC 24G2W1G3- SXINCHA006621",
  mode = "1920x1080@60.00",
  position = "2092x82",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
