# preload = ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/Red_Eclipse.png
# wallpaper = , ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/1-Bonsai-Plant.png
#preload = ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/Bonsai-Plant.png
#wallpaper = , ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/Bonsai-Plant.png
currBGPath=/home/push/backgrounds/

#path = /home/push/backgrounds/Red_Eclipse.png
###
#
wallpaperLeft=$(find "$currBGPath" -type f ! -name "$(basename "$currWallLeft")" | shuf -n 1)
wallpaperRight=$(find "$currBGPath" -type f ! -name "$(basename "$currWallRight")" | shuf -n 1)
#
splash = true
splash_offset = 20
splash_opacity = 0.8
ipc = true

wallpaper {
    monitor = DP-1
    # path = /home/push/backgrounds/Red_Eclipse.png
    path = /home/push/backgrounds/menhirstation.png
    fit_mode = cover
    #timeout = 20
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/push/backgrounds/1-Bonsai-Plant.png
    fit_mode = cover
    #timeout = 22 
}

# wallpaper {
#     monitor = DP-1
#     path = ~/backgrounds/Red_Eclipse.png
#     fit_mode = cover
#     timeout 
# }
#
# wallpaper {
#     monitor = HDMI-A-2
#     path = ~/backgrounds/1-Bonsai-Plant.png
#     fit_mode = cover
# }
#wallpaper {
#    monitor = 
#    path = ~/fallback.jxl
#    fit_mode = cover
#}

# ...
