source = ~/.config/omarchy/current/theme/hyprlock.conf
# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Monospace

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    # contrast = 0.1
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(33ccffee) rgba(00ff99ee) 45deg
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    capslock_color = rgba(ff00ffee) rgba(4c00ffee) 90deg 
    numlock_color = rgba(00fff2ee) rgba(0040ffee) 10deg 

    font_color = rgb(143, 143, 143)
    fade_on_empty = true
    rounding = 15

    font_family = $font
    placeholder_text =
    fail_text = $PAMFAIL $ATTEMPTS
    # fail_text = $PAMFAIL + $LAYOUT + $ATTEMPTS

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true
    
    onclick = hyprctl switchxkblayout all next
    position = 0, -20
    halign = center
    valign = center
}
# PAM fail_text
#label {
#    monitor =
#    text = $PAMFAIL $ATTEMPTS
#    cont_family = $font
#    fail_text = $PAM_AUTH_ERR + $PAMFAIL
#    font_size = 12
#
#    position = -60, 0
#    halign = center
#    valign = center
#  }
# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 45
    font_family = $font

    position = -30, -5
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 20
    font_family = $font

    position = -80, -65
    halign = right
    valign = top
}

label {
    monitor =
    text = |$LAYOUT[de,us]
    font_family = $font
    font_size = 20
    onclick = hyprctl switchxkblayout all next

    position = -30, -65
    halign = right
    valign = top
}

image {
    monitor =
    # border_color = rgba(33ccffee) rgba(00ff99ee)
    border_size = 0 
    path = ~/Wallpaper/Norway_3.jpg
    #path = ~/scripts/changeAvatar.sh
    reload_time = 30 
    reload_cmd = ~/scripts/changeAvatar.sh
    size = 200
    # rounding = -1 # -1 creates a circle
    rounding = 10 


    position = 0, 200
    halign = center
    valign = center
}

#label {
#    monitor =
#    text = $LAYOUT[de,en]
#    font_size = 23
#    onclick = hyprctl switchxkblayout all next
#
#    position = 249, -20
#    halign = center
#    valign = center
#}
