


# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
# windowrule = opacity 0.97 0.9, class:.*
#windowrule = opacity 0.96 0.69, class:.*
windowrule = opacity 0.66 0.19, match:class ghossty
# windowrule = opacity 1.0 override 0.5 override 0.8 override, match:class ghossty
# windowrule = opacity 0.66 0.19, match:class terminal
windowrule = opacity 0.96 0.89, match:class brave-browser
#windowrule = opacity 0.86 0.68, class:^(brave-browser)$
#windowrule = opacity 0.66 0.18, class:^(Ghossty)$
#windowrule = opacity 0.86 0.68, class:^(brave-browser)$

# Fix some dragging issues with XWayland
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# App-specific tweaks
#source = ~/.local/share/omarchy/default/hypr/apps.conf
