# here you can check the kernel behaivor during the plugging moments, plug it and slowly unplug it
watch -n 0.5 "amixer -c 1 contents | grep -i -A2 'jack'"
# Change you config with the below setting and reboot, that will fix your headphonejack issue.
echo "options snd-hda-intel model=,macmini" | sudo tee /etc/modprobe.d/macmini-audio.conf
sudo reboot
