# preload = ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/Red_Eclipse.png
# wallpaper = , ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/1-Bonsai-Plant.png
preload = ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/1-Bonsai-Plant.png
wallpaper = , ~/dotfiles/omarchy/.config/omarchy/current/theme/backgrounds/1-Bonsai-Plant.png
